#!/bin/bash

echo '{"version":1}'
echo '['
run12=0
while [ 0 == 0 ]
do
    printf '['

    # run12 commands first
    if [ "$run12" == "0" ]
    then
        essid="`iwconfig wlp3s0 | awk -F '"' '/ESSID/ {print $2}'`"
        strength="`nmcli -t -f active,ssid,signal dev wifi|grep yes|cut -d':' -f3`"
        vpn_state="`nmcli | grep "tun0: connected to tun0"`"
        doy="`date "+%j"`"
        date="`date "+%F"`"
    fi
    ti="`date "+%I:%M %p"`"
    vol="`amixer -D pulse get Master | grep Left: | cut -d '[' -f2 | cut -d ']' -f1`"
    mute="`amixer -D pulse get Master | grep Left: | cut -d '[' -f3 | cut -d ']' -f1`"

    # WIFI:
    printf '{"name":"wifi","color":"#FFFFFF","full_text":"'"$essid"' '"$strength"'%%"},'

    # VPN:
    if [ "$vpn_state" == "tun0: connected to tun0" ]
    then
        printf '{"name":"vpn","color":"#00FF00","full_text":"VPN: YES"},'
    else
        printf '{"name":"vpn","color":"#FF0000","full_text":"VPN: NO"},'
    fi

    # VOLUME:
    if [ "$mute" != "off" ]
    then
        printf '{"name":"vol","color":"#FFFFFF","full_text":"VOL: '"$vol"'%"},'
    else
        printf '{"name":"vol","color":"#FFFF00","full_text":"MUTED ('"$vol"'%)"},'
    fi

    # DOY:
    printf '{"name":"time","color":"#FF00FF","full_text":"DOY: '"$doy"'"},'

    # DATE:
    printf '{"name":"time","color":"#FFFFFF","full_text":"'"$date"'"},'

    # TIME:
    printf '{"name":"time","color":"#00AAFF","full_text":"'"$ti"' "}'
    printf "],\n"

    # This whole run12 thing is we don't run some commands to often, but let the
    # time and other things run12 every seccond.
    if [ "$run12" == "11" ]
    then
        run12=0
    else
        run12=$((echo "$run"+1 | bc))
    fi
    sleep 5
done
