#!/bin/bash

# See LICENSE for how you can use this.

echo '{"version":1}'
echo '['
counter=0
while true
do
    printf '['

    # counter commands first
    if [ "$counter" == "0" ]
    then
        essid=$(iwconfig wlp3s0 | awk -F '"' '/ESSID/ {print $2}')
        strength=$(nmcli -t -f active,ssid,signal dev wifi|grep yes|cut -d':' -f3)
        vpn_state=$(nmcli | grep "tun0: connected to tun0")
        doy=$(date "+%j")
        date=$(date "+%F")
    fi
    ti=$(date "+%I:%M %p")
    vol=$(amixer -D pulse get Master | grep Left: | cut -d '[' -f2 | cut -d ']' -f1)
    mute=$(amixer -D pulse get Master | grep Left: | cut -d '[' -f3 | cut -d ']' -f1)
    bat=$(upower -i $(upower -e | grep 'BAT') | grep -E "percentage" | cut -d':' -f2 | sed 's/ //g')

    # WIFI:
    printf '{"name":"wifi","color":"#FFFFFF","full_text":"%s %s%%"},' "$essid" "$strength"

    # VPN:
    if [ "$vpn_state" == "tun0: connected to tun0" ]
    then
        printf '{"name":"vpn","color":"#00FF00","full_text":"VPN: YES"},'
    else
        printf '{"name":"vpn","color":"#FF0000","full_text":"VPN: NO"},'
    fi

    # VOLUME:
    if [ "$mute" != "off" ]
    then
        printf '{"name":"vol","color":"#FFFFFF","full_text":"VOL: %s%"},' "$vol"
    else
        printf '{"name":"vol","color":"#FFFF00","full_text":"MUTED (%s%)"},' "$vol"
    fi

    # DOY:
    printf '{"name":"doy","color":"#FF00FF","full_text":"DOY: %s"},' "$doy"

    # DATE:
    printf '{"name":"date","color":"#FFFFFF","full_text":"%s"},' "$date"

    # TIME:
    printf '{"name":"time","color":"#00AAFF","full_text":"%s"},' "$ti"

    # BATTERY
    printf '{"name":"bat","color":"#FFFFFF","full_text":"%s% "}' "$bat"


    printf "],\n"
    # This whole counter thing is we don't run some commands to often
    # (~30secs), but let the time and other things counter every seccond.
    if [ "$counter" -lt "6" ]
    then
        let counter=$counter+1
    else
        counter=0
    fi
    sleep 5
done
